version: "3.9"

services:
  api:
    build: .
    ports:
      - "8444:8444"
    volumes:
      - ./:/workspace
      - orchestrator_data:/app/data
    environment:
      - PYTHONPATH=/app
    working_dir: /app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8444"]

volumes:
  orchestrator_data:
